# Generated by Django 6.0.3 on 2026-03-30 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=30)),
                ('command_name', models.CharField(default='test_crawl', max_length=100)),
                ('status', models.CharField(choices=[('success', '성공'), ('failed', '실패')], max_length=20)),
                ('total_targets', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '크롤링 실행 로그',
                'verbose_name_plural': '크롤링 실행 로그 목록',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('danawa', '다나와'), ('hwahae', '화해'), ('glowpick', '글로우픽')], max_length=30)),
                ('target_type', models.CharField(choices=[('search', '검색 페이지'), ('product', '상품 상세 페이지')], default='search', max_length=20)),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '크롤링 대상',
                'verbose_name_plural': '크롤링 대상 목록',
                'ordering': ['site', 'target_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('item_title', models.CharField(blank=True, max_length=500)),
                ('item_url', models.URLField(blank=True, max_length=1000)),
                ('raw_text', models.TextField(blank=True)),
                ('raw_html', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', to='crawling.crawltarget')),
            ],
            options={
                'verbose_name': '크롤링 원본 데이터',
                'verbose_name_plural': '크롤링 원본 데이터 목록',
                'ordering': ['-crawled_at'],
            },
        ),
    ]
