# Generated by Django 6.0.3 on 2026-03-30 05:07

import hashlib
from django.db import migrations, models


def fill_unique_keys(apps, schema_editor):
    CrawlRawData = apps.get_model('crawling', 'CrawlRawData')
    for obj in CrawlRawData.objects.all():
        raw = f"{obj.id}_{obj.source_url}_{obj.id}"
        obj.unique_key = hashlib.md5(raw.encode()).hexdigest()
        obj.save(update_fields=["unique_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrawdata',
            name='record_type',
            field=models.CharField(choices=[('page_info', '페이지 정보'), ('candidate_link', '후보 링크')], db_index=True, default='candidate_link', max_length=30),
        ),
        # 1단계: unique=True 없이 먼저 추가
        migrations.AddField(
            model_name='crawlrawdata',
            name='unique_key',
            field=models.CharField(blank=True, max_length=255, default=''),
        ),
        # 2단계: 기존 데이터에 고유값 채우기
        migrations.RunPython(fill_unique_keys, migrations.RunPython.noop),
        # 3단계: unique 제약 추가
        migrations.AlterField(
            model_name='crawlrawdata',
            name='unique_key',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='crawlrawdata',
            name='item_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='crawlrawdata',
            name='page_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='crawlrawdata',
            index=models.Index(fields=['target', 'record_type'], name='crawling_cr_target__7917a2_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlrawdata',
            index=models.Index(fields=['source_url'], name='crawling_cr_source__b071b1_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlrawdata',
            index=models.Index(fields=['item_url'], name='crawling_cr_item_ur_e1fde9_idx'),
        ),
    ]
