# Generated by Django 6.0.3 on 2026-03-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_crawlrawdata_record_type_crawlrawdata_unique_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawltarget',
            options={'ordering': ['-priority', 'site', 'target_type', '-created_at'], 'verbose_name': '크롤링 대상', 'verbose_name_plural': '크롤링 대상 목록'},
        ),
        migrations.AddField(
            model_name='crawltarget',
            name='crawl_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='이 target을 다시 수집할 최소 간격(분)'),
        ),
        migrations.AddField(
            model_name='crawltarget',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='숫자가 클수록 우선 수집'),
        ),
    ]
