# Generated by Django 6.0.3 on 2026-04-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_alter_crawltarget_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrawdata',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
    ]
