repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: ^ai-server/.*\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^ai-server/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^ai-server/
      - id: end-of-file-fixer
        files: ^ai-server/
      - id: check-yaml
        files: ^ai-server/.*\.(yml|yaml)$
      - id: check-added-large-files