# ================================
# 🔥 요청 제한 (Rate Limit) 설정
# ================================
limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;

server {
    listen 80;
    server_name _;

    client_max_body_size 20M;

    # ================================
    # 🔒 보안 헤더 추가
    # ================================
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Content-Security-Policy "default-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://product-review-static-hj.s3.amazonaws.com https://product-review-static-hj.s3.ap-northeast-2.amazonaws.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://product-review-static-hj.s3.amazonaws.com https://product-review-static-hj.s3.ap-northeast-2.amazonaws.com; connect-src 'self' https://cdn.jsdelivr.net; img-src 'self' data: https://product-review-static-hj.s3.amazonaws.com https://product-review-static-hj.s3.ap-northeast-2.amazonaws.com https://product-review-media-hj.s3.amazonaws.com https://product-review-media-hj.s3.ap-northeast-2.amazonaws.com; font-src 'self' data: https://product-review-static-hj.s3.amazonaws.com https://product-review-static-hj.s3.ap-northeast-2.amazonaws.com;" always;
    server_tokens off;

    # ================================
    # 🚫 공격 경로 차단
    # ================================
    location ~* \.php$ {
        return 444;
    }

    location ~* /(wp-admin|phpunit|vendor|cgi-bin|backup|\.env) {
        return 444;
    }

    location ~ /\. {
        deny all;
    }

    # ================================
    # 📁 static 파일
    # ================================
    location /static/ {
        alias /app/staticfiles/;
    }

    # ================================
    # 📁 media 파일
    # ================================
    location /media/ {
        alias /app/media/;
    }

    # ================================
    # 🤖 FastAPI 서버
    # ================================
    location /ai/ {
        proxy_pass http://fastapi-server:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        limit_req zone=one burst=10 nodelay;
    }

    # ================================
    # 🌐 Django 서버
    # ================================
    location / {
        proxy_pass http://drf-web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        limit_req zone=one burst=10 nodelay;
    }
}