# Generated by Django 6.0.3 on 2026-03-26 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reviewai',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reviewai',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
